name: Main

on:
  push:
    branches: [main]

jobs:
  build:
    name: Version and Build
    if: "!contains(github.event.head_commit.message, 'chore(release)')"
    runs-on: self-hosted
    env:
      DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
      CR_PAT: ${{ secrets.CR_PAT }}
      CR_USER: ${{ secrets.CR_USER }}
    steps:
      - uses: actions/checkout@v2
        name: Checkout
        with:
          fetch-depth: 0
          token: ${{ secrets.GIT_TOKEN }}
      - uses: actions/setup-node@v3
        name: Setup Node
        with:
          node-version: 16
      - uses: borales/actions-yarn@v3.0.0
        name: Install dependencies
        with:
          cmd: install
      - name: Import GPG Key
        uses: crazy-max/ghaction-import-gpg@v5.2.0
        with:
          gpg_private_key: ${{secrets.GPG_KEY}}
          passphrase: ${{secrets.GPG_PASS}}
          git_committer_name: ${{secrets.GIT_NAME}}
          git_committer_email: ${{secrets.GIT_EMAIL}}
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_tag_gpgsign: true
      - name: Bump version
        env:
          GITHUB_TOKEN: ${{secrets.GIT_TOKEN}}
        run: |
          git config --local gpg.program $(which gpg)
          npm run release
      - uses: docker/login-action@v1
        name: Login to docker registry
        with:
          registry: ${{secrets.DOCKER_REGISTRY}}
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
      - name: Login to ghcr.io registry
        run: echo $CR_PAT | docker login ghcr.io -u $CR_USER --password-stdin
      - name: Build docker images
        run: yarn build:docker
      - name: Push docker images
        run: |
          docker images --filter "reference=$DOCKER_REGISTRY/cdn:latest" --format {{.Repository}} | xargs -I IMG docker image push --all-tags IMG > /dev/null
          docker images --filter "reference=ghcr.io/eyzi/cdn:latest" --format {{.Repository}} | xargs -I IMG docker image push --all-tags IMG > /dev/null
      - name: Push new version
        env:
          GITHUB_TOKEN: ${{secrets.GIT_TOKEN}}
        run: git push --follow-tags origin ${{github.ref_name}}
      - name: Clean docker images
        run: |
          docker rmi -f $(docker images --filter "reference=$DOCKER_REGISTRY/cdn" --format {{.ID}}) > /dev/null
          docker rmi -f $(docker images --filter "reference=ghcr.io/eyzi/cdn" --format {{.ID}}) > /dev/null
        continue-on-error: true
